### PR TITLE
code commited for mini lesson

### PR DESCRIPTION
**Pull request by kuldeepbanga19**

### CODE REVIEW

**Review by justinhunt — CHANGES_REQUESTED** [review]
Thanks Kuldeep.

Can I ask for a few changes?

classes/dates.php
This contains code that imports from mod_assign (line 47). And it creates and uses an instance of mod_assign (line 51).  I dont think there needs to be any relation to mod_assign in this class. Please remove all references to it, replace them with any necessary code to achieve the same thing from minilesson, and give it a test.

db/access.php
There already is a "canpreview" capability which seems to do the same thing as the "preview" capability that you added. Is there a reason that we need the new capability? If not, please just use canpreview. If yes, then I think we also need a lang string for the new capability
eg $string['minilesson:preview'] = 'Can preview MiniLesson activities';

db/upgrade.php
There is an artifact of a copy/past job here and it refers to readaloud:
  upgrade_mod_savepoint(true, 2022020100, 'readaloud');
This will cause trouble, so please change that "readaloud" to "minilesson"

I see you also merged with the latest code. Thanks I had to make a few changes while you were working.

**Review by kuldeepbanga19 — COMMENTED** [review]
Please review the code

**Review by kuldeepbanga19 — COMMENTED** [review]
Please review

**Review by justinhunt — APPROVED** [review]
looks good

**Pull request merged**
